default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>

production:
  <<: *default
  database: db_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>